module.exports = {
  entry: {
    'functions/add-shipment': './functions/add-shipment.js',
    'functions/get-shipment': './functions/get-shipment.js',
    'functions/get-shipmentByParty': './functions/get-shipmentByParty.js',
    'functions/deliver-shipment': './functions/deliver-shipment.js',
    'functions/receive-shipment': './functions/receive-shipment.js',
    'functions/get-shipmentMovements': './functions/get-shipmentMovements.js',
    'functions/add-sensorData': './functions/add-sensorData.js',
    'functions/get-sensorData': './functions/get-sensorData.js',
    'functions/get-auditTrail': './functions/get-auditTrail.js',
    'functions/add-insuranceClaim': './functions/add-insuranceClaim.js',
    'functions/get-claimData': './functions/get-claimData.js',
    'functions/get-recentShipments': './functions/get-recentShipments.js',
    'functions/add-sensorDataSimulation': './functions/add-sensorDataSimulation.js',
    'functions/notify-highRiskShipments': './functions/notify-highRiskShipments.js',
    'functions/get-highRiskShipments': './functions/get-highRiskShipments.js',
    'functions/get-shipmentCount': './functions/get-shipmentCount.js',
    'functions/get-claimCount': './functions/get-claimCount.js',
    'functions/get-recentClaims': './functions/get-recentClaims.js',
    'functions/get-graphInfo': './functions/get-graphInfo.js',
    'functions/get-trackingProvenance': './functions/get-trackingProvenance.js',
    'functions/add-retailerShipments': './functions/add-retailerShipments.js',
    'functions/get-shipmentCountByParty': './functions/get-shipmentCountByParty.js',
    'functions/get-claimCountByParty': './functions/get-claimCountByParty.js',
    'functions/get-recentClaimsByParty': './functions/get-recentClaimsByParty.js',
    'functions/get-highRiskShipmentsByParty': './functions/get-highRiskShipmentsByParty.js',
    'functions/get-shipmentLocationByParty': './functions/get-shipmentLocationByParty.js',
    'functions/get-shipmentRoute': './functions/get-shipmentRoute.js',
    'functions/get-temperatureGraph': './functions/get-temperatureGraph.js',
    'functions/get-humidityGraph': './functions/get-humidityGraph.js',
  },
  mode: 'production',
  target: 'node',
};
